### ISSUE TITLE
solidity tricky

### ISSUE THREAD

**Issue by Block-Expert** [Block-Expert/solidity-challenge#2]
Hi all.
What's the meaning of the calldata in solidity?
I don't know the meaning of the calldata exactly.
Please let me know the meaning of the calldata and its usage.
Thanks

**Comment by senichevalexey** [comment]
Hi, it should help you
https://docs.soliditylang.org/en/v0.8.17/types.html?highlight=calldata#data-location

**Comment by Block-Expert** [comment]
Hi @senichevalexey , thanks a lot.
I have one more question.
How can I call the contract function which has calldata as parameter?
